# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ğŸ§‘ğŸ»â€ğŸ’»íƒ¤ë¡œìš° ì›”ë“œ
brief-intro: Android Developer
baseurl: /
url: https://taehyungk.github.io

permalink: /:year/:month/:day/:title/

# other links
twitter_username:
facebook_username:
github_username:  TaeHyungK
email: xogud3125@naver.com
weibo_username:
zhihu_username:
linkedIn_username:
dribbble_username:

description_footer:

# comments
# two ways to comment, only choose one, and use your own short name
duoshuo_shortname: #TaeHyungK's Blog
disqus_shortname: TaeHyungK

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6

# google analytics setting
google_analytics_id: UA-168858803-1